=== 0c0w3/mozilla-pipeline-schemas/telemetry/main-v1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "application": {
      "$ref": "application-main-v1.schema.json#/application"
    },
    "clientId": {
      "type": "string"
    },
    "creationDate": {
      "type": "string"
    },
    "environment": {
      "$ref": "environment-main-v1.schema.json#/environment"
    },
    "id": {
      "type": "string"
    },
    "meta": {
      "type": "object"
    },
    "payload": {
      "type": "object"
    },
    "type": {
      "type": "string"
    },
    "version": {
      "type": "number"
    }
  },
  "required": ["application", "creationDate", "id", "version"]
}

=== 0c0w3/mozilla-pipeline-schemas/validation/telemetry/block-autoplay.1.prompt.pass.json
{
  "type": "block-autoplay",
  "id": "36d2c19a-30d0-f441-88cf-5c477de3275e",
  "creationDate": "2018-08-21T21:25:43.172Z",
  "version": 4,
  "clientId": "71b6cac2-b7fb-f04e-9768-366ab51d3cfa",
  "application": {
    "architecture": "x86-64",
    "buildId": "20180821100053",
    "name": "Firefox",
    "version": "63.0a1",
    "displayVersion": "63.0a1",
    "vendor": "Mozilla",
    "platformVersion": "63.0a1",
    "xpcomAbi": "x86_64-gcc3",
    "channel": "nightly"
  },
  "payload": {
    "id": 10,
    "branch": "allow-and-notRemember",
    "payload": {
      "type": "prompt",
      "promptResponse": [
        {
          "pageId": "a8252bd8ac60de9f901001773db53cf5e4dddf9bd9c056d0b00cb749f81b649a",
          "timestamp": 1532567717284,
          "rememberCheckbox": false,
          "allowAutoplay": false
        },
        {
          "pageId": "a8252bd8ac60de9f901001773db53cf5e4dddf9bd9c056d0b00cb749f81b649a",
          "timestamp": 1532567719828,
          "rememberCheckbox": true,
          "allowAutoplay": true
        },
        {
          "pageId": "a8252bd8ae60de9f901gy1773db53cf5e4dddf9bd9c056d0b00cb749f81b649a",
          "timestamp": 1532567819828,
          "rememberCheckbox": false,
          "allowAutoplay": true
        }
      ]
    }
  }
}
